config/routes.rb
Androidparts::Application.routes.draw do
  root :to => 'searches#new'

  resources :searches, :only => [:new, :index]
  resource :session, :only => [:new, :create, :destroy]
  resources :maintainers, :only => [:edit,:update]
  resources :packages do
    resources :versions, :only => [:new, :create]
  end

end

app/models/maintainer.rb
class Maintainer < ActiveRecord::Base
  belongs_to :organization
  has_many :packages

  validates_presence_of :organization_id, :if => :complete?

  def complete?
    name.present? && email.present?
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :maintainers
end

app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :maintainer
  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings
  has_many :versions

  accepts_nested_attributes_for :versions

  validates_presence_of :maintainer_id

  delegate :number, :date, :to => :newest_version, :prefix => true
  delegate :license, :license_url, :to => :newest_version

  ### TODO: maintainer, org, license
  def self.search(query)
    select('packages.*').
      where(<<-HERE, :query => query.downcase)
        lower(packages.name) = :query
        OR :query IN (
          SELECT lower(tags.name) FROM tags
          JOIN taggings ON taggings.tag_id = tags.id
          WHERE taggings.taggable_id = packages.id
          AND taggings.taggable_type = 'Package'
        )
      HERE
  end

  def maintainer_name
    maintainer.name
  end

  def organization_name
    maintainer.organization.name
  end

  def newest_version
    versions.newest
  end

  def jar
    newest_version.jar
  end

  def jar_url
    jar.url
  end

  def doc
    newest_version.doc
  end

  def doc_url
    doc.url
  end
end

app/models/search.rb
class Search
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :query

  def initialize(opts = {})
    opts.each do |k,v|
      send("#{k}=", v)
    end
  end

  def persisted?
    false
  end

  def results
    Package.search(self.query)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :taggable, :polymorphic => true
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :package
  has_attached_file :jar
  has_attached_file :doc

  def self.by_created_at
    order('created_at ASC')
  end

  def self.newest
    by_created_at.first
  end

  def self.build_from_prior
    if prior = last
      self.new(:min_sdk => prior.min_sdk, :license => prior.license, :license_url => prior.license_url)
    else
      self.new
    end
  end

  def date
    created_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def store_location(l)
    session[:stored_location] = l
  end

  def store_location!
    store_location(url_for)
  end

  def stored_location
    session[:stored_location]
  end

  def clear_stored_location!
    session[:stored_location] = nil
  end

  def redirect_back_or(or_url)
    redirect_to(stored_location || or_url)
    clear_stored_location!
  end

  def current_maintainer
    @_current_maintainer ||= Maintainer.find(session[:maintainer_id])
  end

  def signed_in?
    session[:maintainer_id].present?
  end
  helper_method :signed_in?

  def signed_out?
    !signed_in?
  end

  def ensure_authenticated
    if signed_out?
      store_location!
      flash[:failure] = 'You must be signed in.'
      redirect_to new_session_url
    end
  end
end

app/controllers/maintainers_controller.rb
class MaintainersController < ApplicationController
  def edit
    @maintainer = Maintainer.find(params[:id])
  end

  def update
    @maintainer = Maintainer.find(params[:id])
    if @maintainer.update_attributes(params[:maintainer])
      redirect_back_or root_url
    else
      render :edit
    end
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_filter :ensure_authenticated, :only => [:index, :new, :create, :edit, :update]

  def show
    @package = Package.find(params[:id])
  end

  def index
    @packages = current_maintainer.packages
  end

  def new
    @package = current_maintainer.packages.new
    @package.versions.build
  end

  def create
    @package = current_maintainer.packages.build(params[:package])
    if @package.save
      redirect_to @package
    else
      render :new
    end
  end

  def edit
    @package = current_maintainer.packages.find(params[:id])
  end

  def update
    @package = current_maintainer.packages.find(params[:id])
    if @package.update_attributes(params[:package])
      redirect_to packages_path(@package)
    else
      render :edit
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  respond_to :html, :xml, :only => :index

  def new
    @search = Search.new
    render :layout => 'home'
  end

  def index
    @search = Search.new(params[:search])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if resp = request.env['rack.openid.response']
      if resp.status == :success
        handle_maintainer(resp.display_identifier)
      else
        flash[:failure] = "OpenID authentication failed: #{resp.status}"
        render :new
      end
    else
      openid_header = Rack::OpenID.build_header(
        :identifier => params['openid_identifier'])
      response.headers['WWW-Authenticate'] = openid_header
      render :nothing => true, :status => 401
    end
  end

  def destroy
    session[:maintainer_id] = nil
    redirect_to root_url
  end

  protected

  def handle_maintainer(openid)
    maintainer = Maintainer.find_by_openid_identifier(openid)
    if maintainer && maintainer.complete?
      session[:maintainer_id] = maintainer.id
      redirect_back_or root_url
    else
      maintainer ||= Maintainer.create!(:openid_identifier => openid)
      session[:maintainer_id] = maintainer.id
      redirect_to edit_maintainer_url(maintainer)
    end
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def new
    @package = current_maintainer.packages.find(params[:package_id])
    @version = @package.versions.build_from_prior
  end

  def create
    @package = current_maintainer.packages.find(params[:package_id])
    @version = @package.versions.build(params[:version])
    if @version.save
      redirect_to @package
    else
      render :new
    end
  end
end

app/helpers/body_class_helper.rb
module BodyClassHelper
  # TODO: move this into a gem/plugin
  def body_class
    qualified_controller_name = controller.controller_path.gsub('/','-')
    "#{qualified_controller_name} #{qualified_controller_name}-#{controller.action_name}"
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def link_tags(tags)
    tags.map do |tag|
      link_to(tag.name, searches_path(:search => {:query => tag.name}))
    end.join(', ').html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>androidparts</title>
  <%= stylesheet_link_tag 'screen', :media => 'all', :cache => true %>
  <%= javascript_include_tag "jquery", "jquery-ui", "prefilled_input", "rails", "application", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= body_class %>">
  <%= render :partial => 'shared/flashes' -%>
  <%= yield %>
  <%= render :partial => 'shared/javascript' %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>androidparts</title>
  <%= stylesheet_link_tag 'screen', :media => 'all', :cache => true %>
  <%= javascript_include_tag "jquery", "jquery-ui", "prefilled_input", "rails", "application", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= body_class %>">
  <%= render :partial => 'shared/flashes' -%>
  <%= yield %>
  <%= render :partial => 'shared/javascript' %>
</body>
</html>

app/views/maintainers/edit.html.erb
<%= semantic_form_for @maintainer do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :email %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button 'Complete Registration' %>
  <% end %>
<% end %>

app/views/searches/_nav.html.erb
<ul>
  <% if signed_in? %>
    <li><%= link_to 'Sign out', session_path, :method => :delete %></li>
    <li><%= link_to 'Submit', new_package_path %></li>
    <li><%= link_to 'Packages', packages_path %></li>
  <% else %>
    <li><%= link_to 'Sign in', new_session_path %></li>
  <% end %>
  <li><%= link_to 'Advanced', '#' %></li>
  <li><%= link_to 'Contact', '#' %></li>
</ul>

app/views/searches/index.html.erb
<%= content_for :title, "#{@search.query} - Android Parts" %>

<%= semantic_form_for @search, :html => {:method => :get} do |form| %>
  <%= form.inputs do %>
    <%= form.input :query %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button 'Search within' %>
    <%= form.commit_button 'Search globally' %>
  <% end %>
<% end %>


<%= render :partial => :package, :collection => @search.results %>

<%= render :partial => 'nav' %>

app/views/searches/new.html.erb
<%= content_for :title, "Android Parts" %>

<%= semantic_form_for @search, :html => {:method => :get} do |form| %>
  <%= form.inputs do %>
    <%= form.input :query %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button 'Search' %>
  <% end %>
<% end %>

<%= render :partial => 'nav' %>

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%=h value %></div>
  <% end -%>
</div>

app/views/shared/_javascript.html.erb
<%= javascript_include_tag 'jquery', 'jquery-ui', 'prefilled_input',  :cache => true %>
<%= yield :javascript %>

app/views/versions/new.html.erb
<%= semantic_form_for [@package,@version], :html => {:multipart => true} do |form| %>
  <%= form.inputs do %>
    <%= form.input :number %>
    <%= form.input :min_sdk %>
    <%= form.input :license %>
    <%= form.input :license_url %>
    <%= form.input :jar, :as => :file %>
    <%= form.input :doc, :as => :file, :label => 'Documentation (JAR or Zip)' %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button 'Publicize' %>
  <% end %>
<% end %>